// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9psUXQULLBO6XEtjGrDkoZN9DND5zew',
    appId: '1:856478705019:web:6e3321ad70346a237bc9de',
    messagingSenderId: '856478705019',
    projectId: 'my-chatapp-being-better',
    authDomain: 'my-chatapp-being-better.firebaseapp.com',
    storageBucket: 'my-chatapp-being-better.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk0nzbQ_RBCtfAF8_Ur1oR9nY0aOF_kpM',
    appId: '1:856478705019:android:8a537bdc03026ebe7bc9de',
    messagingSenderId: '856478705019',
    projectId: 'my-chatapp-being-better',
    storageBucket: 'my-chatapp-being-better.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjDJk2d3VO6lFiHtN9i8fomcbVvMD4yYc',
    appId: '1:856478705019:ios:276cf7801f3b25687bc9de',
    messagingSenderId: '856478705019',
    projectId: 'my-chatapp-being-better',
    storageBucket: 'my-chatapp-being-better.appspot.com',
    iosClientId: '856478705019-kmv85umo6he9gonoooa2iicf9a5n69ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjDJk2d3VO6lFiHtN9i8fomcbVvMD4yYc',
    appId: '1:856478705019:ios:276cf7801f3b25687bc9de',
    messagingSenderId: '856478705019',
    projectId: 'my-chatapp-being-better',
    storageBucket: 'my-chatapp-being-better.appspot.com',
    iosClientId: '856478705019-kmv85umo6he9gonoooa2iicf9a5n69ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
